### ISSUE TITLE
Enable RLS or do not expose `SUPABASE_KEY`

### ISSUE THREAD

**Issue by amalshaji** [surgieboi/foundersmash#1]
@surgieboi 

Supabase security measures are not enabled, so I can grab the supabase_key from the headers, connect to your Postgres instance, and execute queries. 

For demo, I have added myself to the list (apologies, as this is my way of demonstrating a table mutation). 

<img width="1624" alt="Screenshot 2022-10-10 at 11 09 38 PM" src="https://user-images.githubusercontent.com/18011385/194924024-b914917f-7762-4a59-9de9-5ff7990d7a7a.png">

**Comment by surgieboi** [comment]
good catch @amalshaji 🙌 and thank you!

also, I've enabled RSL for all tables and updated the readme documentation too.
